services:
  app:
    image: todo-front-dev
    build:
      dockerfile: dev.Dockerfile
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-front-dev
