services:
  app:
    image: todo-front-dev
    build:
      context: ./todo-frontend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-front-dev

  nginx:
    container_name: reverse-proxy
    image: nginx:1.20.1
    volumes: # use this nginx.dev.conf when orchestrating front + back together
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on: # wait for the front-end and back-end to be started
      - app
      - server

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    command: ["redis-server", "--appendonly", "yes"]
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

  server:
    image: todo-backend-dev
    build:
      context: ./todo-backend/
      dockerfile: ./dev.Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    volumes:
      - ./todo-backend/:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo

volumes:
  mongo_data:
  redis_data:
